# Inserts a blank line between shell prompts
add_newline = true

# Make prompt a single line instead of two
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "

# Disable showing the current python version
[python]
disabled = true

# Disable showing command duration 
[cmd_duration]
disabled = true

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[localip]
ssh_only = true
format = "[$localipv4](bold red) "
disabled = false
