
require("settings")
require("plugins")
require("mappings")
require("lsp-config")
require("autocompletion")
require("startify-config")
require("treesitter")
require("gitsigns-config")
require("telescope-config")
