require("settings")
require("plugins")
require("mappings")
require("lsp-config")
require("dap-config")
require("autocompletion")
-- require("startify-config")
require("treesitter")
-- require("gitsigns-config")
require("telescope-config")
require("nvim-tree-config")
require("oil-config")
