#!/bin/sh
# alias j='z'
# alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias vimrc='nvim ~/.config/nvim/'

# get fastest mirrors
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
# alias grep='grep --color=auto'
# alias egrep='egrep --color=auto'
# alias fgrep='fgrep --color=auto'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

if [[ $TERM == "xterm-kitty" ]]; then
  alias ssh="kitty +kitten ssh"
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias ls='ls -A'
alias l='ls -CF'

alias ros='. /opt/ros/noetic/setup.bash'
alias ros2='source /opt/ros/foxy/setup.bash'
alias fms='source $HOME/packages/fms/install/setup.bash'
alias ipa_nav='source $HOME/packages/ipa_navigation_ws/devel/setup.bash'
alias backend='conda activate backend'
alias str='
export ROBOT=str_v3
export ROBOT_ENV=bmw-factory
source $HOME/packages/bmw_ws/devel/setup.bash
'
alias ros1rviz='
source $HOME/packages/bmw_ws/devel/setup.bash
roslaunch bmwstr_bringup rviz.launch localization_backend:=lts_ng robot:=str_v3
'


alias weather='curl -4 http://wttr.in/Stuttgart'

alias cppcheck_this='docker run -v$(pwd):/src:ro registry.gitlab.cc-asp.fraunhofer.de/ipa323_internal/ci_images/cppcheck cppcheck --quiet --error-exitcode=2 --library=googletest /src'

alias stop_containers='
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
'

