#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=100000
SAVEHIST=500
export MANWIDTH=999

# set default apps
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="brave"
export MANPAGER='nvim +Man!'

# include binary paths
export PATH="/usr/lib/ccache":$PATH
export PATH="${HOME}/.local/bin":$PATH
export PATH="${HOME}/.cargo/bin":$PATH

# set workspace directory for aliases
export WSDIR="${HOME}/git"

# export PATH=$HOME/.local/share/go/bin:$PATH
# export GOPATH=$HOME/.local/share/go
# export PATH=$HOME/.fnm:$PATH
# export PATH="$PATH:./node_modules/.bin"

# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

export GTEST_COLOR=1

# needed to make ssh-agent discoverable
# export SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}openssh_agent

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        source "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

#source /opt/ros/noetic/setup.zsh
